/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uchicago_cs_encsel_query_offheap_EqualJniScalar */

#ifndef _Included_edu_uchicago_cs_encsel_query_offheap_EqualJniScalar
#define _Included_edu_uchicago_cs_encsel_query_offheap_EqualJniScalar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uchicago_cs_encsel_query_offheap_EqualJniScalar
 * Method:    execute
 * Signature: (Ljava/nio/ByteBuffer;II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_edu_uchicago_cs_encsel_query_offheap_EqualJniScalar_execute
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
